# Convert to https://github.com/Homebrew/homebrew-bundle ?

# services external command
brew tap homebrew/services
brew tap homebrew/command-not-found

# wine
#brew install winetricks

# Development
brew install python
brew install nvm node
#brew install mysql
#brew install postgresql pgcli
brew install jd # json diff tool - test it
brew install awscli
brew install fx jq qp # JSON tools - test qp, a sql like syntax for json quering
brew install howdoi
brew install gpg # GnuPGP
brew install http-prompt

# Vim
brew install luarocks cmake # neovim build dependencies
brew install vim neovim
brew install ctags
brew install tidy-html5
brew install shellcheck # for vim shell static check

# perl for neovim
brew install perl cpanm
export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
cpan local::lib
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
cpanm -n Neovim::Ext


# Shells
brew install zsh zsh-completions zinit
brew install bash
brew install bash-completion@2

# Completions
brew install rails-completion rake-completion bundler-completion gem-completion pip-completion \
             ruby-completion vagrant-completion tmuxinator-completion grunt-completion django-completion \
             packer-completion spring-completion brew-cask-completion open-completion \
             launchctl-completion fabric-completion stormssh-completion \
             yarn-completion docker-completion

# git
brew install git git-flow-avh diff-so-fancy git-sizer onefetch
brew install lazygit
brew install svn
brew install gh # GitHub CLI

brew tap "rhysd/git-brws" "https://github.com/rhysd/git-brws"
brew install git-brws # Cool browsing command for git

# Command line tools
brew install wget coreutils rename tree cheat stormssh dos2unix prettyping pstree lsusb \
             gawk telnet findutils grep gnu-sed gnu-tar htop tcping lunchy-go ipinfo-cli
brew install fd # better find
brew install bat # better cat
brew install exa # better ls
brew install ncdu # NCurses Disk Usage
brew install speedtest-cli
brew install aria2 # download accelerator
brew install broot # a new way to search files - use br
#brew install TomAnthony/brews/itermocil - is broken...

# Command line enhancement
#brew install antigen
brew install starship
brew install ripgrep-all the_platinum_searcher the_silver_searcher
#brew install tmux
brew install fzf # consider peco https://github.com/peco/peco

# Install shell extensions - this should be done whenever fzf is updated
$(brew info fzf | grep /install)

# K8s
#brew install kubectl helm helmfile
#brew install terraform_landscape terraform-docs terraformer terraforming
#brew install docker-clean
brew install lazygit lazydocker skanehira/docui/docui gitui
#brew install liamg/tfsec/tfsec
#brew install tflint
#brew install pre-commit
#npm install -g markdown-link-check
#kube-aws gimme-aws-creds awsume
brew install tfenv
brew install iam-policy-json-to-terraform
brew install minamijoyo/tfupdate/tfupdate # a tool to update TF version constraints
brew install hashicorp/tap/terraform-ls

# TF tools to test:
#https://github.com/flosell/iam-policy-json-to-terraform
#https://github.com/minamijoyo/tfschema
#https://github.com/minamijoyo/tfupdate
#https://github.com/hieven/terraform-visual

# Security Tools
brew install ccheck ssllabs-scan testssl sslyze


########
# apps #
########

# Graphviz - tool for graphs
brew install graphviz

# asciinema - record the terminal
brew install asciinema

# Tool for backing up mac
#brew install mackup

# Check:
# aws-okta
# docker-credential-helper-ecr
# serverless


