brew tap homebrew/dupes

# services external command
brew tap homebrew/services

# desc external command
brew tap telemachus/homebrew-desc

# meld
brew install python --universal --with-brewed-openssl --with-brewed-tk
brew install pygtk --universal
brew install homebrew/x11/meld hicolor-icon-theme

# wine
brew install wine --devel
brew install winetricks

# Other apps
brew install mysql node macvim postgresql

# Shells
brew install zsh zsh-completions
brew install bash
brew install homebrew/versions/bash-completion2

# Completions
brew tap homebrew/completions
brew install rails-completion rake-completion bundler-completion gem-completion pip-completion \
             ruby-completion vagrant-completion tmuxinator-completion grunt-completion django-completion \
             docker-completion packer-completion spring-completion

# git
brew install git git-flow-avh hub

# Tools
brew install wget coreutils md5sha1sum rename tree cheat the_platinum_searcher
brew install findutils homebrew/dupes/grep gnu-sed --with-default-names

# Command line enhancement
brew install liquidprompt autojump stormssh osquery
#brew install tmux
brew install fzf # consider peco https://github.com/peco/peco

# Install shell extensions - this should be done whenever fzf is updated
$(brew info fzf | grep /install)

# todo - TRIAL
brew install todo-txt
brew install googlecl


########
# apps #
########

# Graphviz - tool for graphs
brew install graphviz

# Tool for backing up mac
brew install mackup

# Download subtitles for movies
brew install submarine subliminal


#
# PowToon
#
brew install geoip

############
# Finalize #
############

# link to apps folder
brew linkapps

